<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "publist4ubma2"
 *
 * Auto generated by Extension Builder 2016-06-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'publist4ubma2',
	'description' => 'Extbase + fluid based version of publist4ubma
Outputs a embedded list of publications by taking data from 
http://ub-madoc.bib.uni-mannheim.de/',
	'category' => 'plugin',
	'author' => 'Sebastian Kotthoff',
	'author_email' => 'sebastian.kotthoff@rz.uni-mannheim.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
