<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "uma_publist"
 *
 * Auto generated by Extension Builder 2016-06-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'uma_publist',
	'description' => 'Publication List Module
Synchronizes and displays publication lists using data from
http://ub-madoc.bib.uni-mannheim.de/',
	'category' => 'plugin',
	'author' => 'Sebastian Kotthoff',
	'author_email' => 'sebastian.kotthoff@rz.uni-mannheim.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.9.99',
			'vhs' => '3.0.0-4.9.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
